### ISSUE TITLE
Paytm screen exits automatically after getting OTP.

### ISSUE THREAD

**Issue by riskyRahul** [mrdishant/Paytm-All-in-one-flutter-sdk#12]
Hello. Friends, I have a problem with this library, please help me. I have this kind of exception

- My Flutter version is :- {Flutter (**Channel master, 1.22.0-10.0.pre.39**, on Microsoft Windows [Version 10.0.18363.1139], locale en-GB)}
- Flutter Paytm librery version is:- {**paytm: ^1.0.7**}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

D/AssistLogs(14200): com.paytm.pgsdk.PaytmPGActivity$SmsConsentBroadCastReciever@b10e141:Receiver started:
D/AndroidRuntime(14200): Shutting down VM
E/AndroidRuntime(14200): FATAL EXCEPTION: main
E/AndroidRuntime(14200): Process: com.example.pro_advisor, PID: 14200
E/AndroidRuntime(14200): java.lang.RuntimeException: Unable to start receiver com.oohyugi.sms_otp_auto_verify.SmsBroadcastReceiver: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
E/AndroidRuntime(14200): at android.app.ActivityThread.handleReceiver(ActivityThread.java:4111)
E/AndroidRuntime(14200): at android.app.ActivityThread.access$1700(ActivityThread.java:242)
E/AndroidRuntime(14200): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2078)
E/AndroidRuntime(14200): at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(14200): at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(14200): at android.app.ActivityThread.main(ActivityThread.java:7830)
E/AndroidRuntime(14200): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14200): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(14200): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
E/AndroidRuntime(14200): Caused by: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
Lost connection to the device.

**Comment by mrdishant** [comment]
Plugin updated. Have a look and let me know.

**Comment by MaheshPeri19** [comment]
I am having same issue now. Using paytm: ^2.0.0 version. After entering mobile number, it is asking alert to accept for sms. At that time app is crashing and getting same above logs.

**Comment by MaheshPeri19** [comment]
I found exact issue. Paytm package is clashing with sms_otp_auto_verify package.

By running example project of paytm, it is working fine for production. But when i use it in my app, it is getting above error. Bcz i also used sms auto verify package.

@riskyRahul 
Did you use sms_otp_auto_verify: ^1.2.2 in your project ?

**Comment by MaheshPeri19** [comment]
Update :  

Issue is not related to paytm sdk. It is with sms_otp_auto_verify.

```
In sms_otp_auto_verify ====> SmsBroadcastReceiver.kt file ===>  line no 28, change from below line

val sms: String? = extras.get(SmsRetriever.EXTRA_SMS_MESSAGE) as String
to this line.
val sms: String? = extras.get(SmsRetriever.EXTRA_SMS_MESSAGE) as? String
```

Just added question mark after "as" solved this issue.
